### ISSUE TITLE
[Application] : Sameer

### ISSUE THREAD

**Issue by sameerbk** [fuel-champions/pro-applications#19]
### Proof of your code

Github.com/sameerbk

### Activity on the Fuel forum

Not active 

### Fuel Ambassador Program

No, I'm not a Fuel Ambassador

### Trivia Question

To deploy reusable code as a library

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
We appreciate your interest in the Fuel Developer Champions Program. At this time, we are unable to proceed with your application due to the lack of demonstrated coding activity. However, we encourage you to get involved in our open-source projects at [Fuel Labs on GitHub](https://github.com/fuellabs). Engaging with these projects can be a great way to develop your skills and contribute to the community. We look forward to seeing your growth and hope you'll consider reapplying to the program in the future. Keep coding and stay inspired!
