### ISSUE TITLE
[Application] : 

### ISSUE THREAD

**Issue by xlzy905** [fuel-champions/pro-applications#64]
### Proof of your code

https://github.com/FuelLabs/fuel-explorer/pull/260#event-12289354376

I am interested in fuel stacks and have been familiar with the fuel ecosystem and looking for areas to contribute to.These are some minor contributions I have made to the fuel explorer issue. I am familiar with the engineering architecture and solve problems

### Fuel Ambassador Program

None

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
We appreciate your interest in the Fuel Developer Champions Program. At this time, we are unable to proceed with your application due to the lack of demonstrated coding activity. However, we encourage you to get involved in our open-source projects at [Fuel Labs on GitHub](https://github.com/fuellabs). Engaging with these projects can be a great way to develop your skills and contribute to the community. We look forward to seeing your growth and hope you'll consider reapplying to the program in the future. Keep coding and stay inspired!
