### ISSUE TITLE
[Application] : web3 dev,Want to build the fuel together

### ISSUE THREAD

**Issue by Oldwarma** [fuel-champions/pro-applications#68]
### Proof of your code

https://github.com/Oldwarma/Participating-projects/tree/master  Hackathon project
https://github.com/Oldwarma/memento-master  Memento is a tool used to load and save accounts from old Solana snapshots in Google Cloud Storage.

### Activity on the Fuel forum

https://forum.fuel.network/u/oldwarma/summary

### Fuel Ambassador Program

None

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
We appreciate your interest in the Fuel Developer Champions Program. At this time, we are unable to proceed with your application due to the lack of demonstrated coding activity. However, we encourage you to get involved in our open-source projects at [Fuel Labs on GitHub](https://github.com/fuellabs). Engaging with these projects can be a great way to develop your skills and contribute to the community. We look forward to seeing your growth and hope you'll consider reapplying to the program in the future. Keep coding and stay inspired!
